name = "khanqah-site"
pages_build_output_dir = "."
compatibility_date = "2026-08-23"

[[d1_databases]]
binding = "DB"
database_name = "murtaza_notifications"
database_id = "be765a26-0e26-45f5-a146-6121da3874fc"

[vars]
VAPID_PUBLIC_KEY = "BJaY60hjsCZ6aWyQH6smChVTO2dplKLbg0ZxGbvRZEVgvSeLlcxdfvdU-ytqddGpM1rGXd5shUg-cSudxgeuQ5A"
VAPID_SUBJECT = "https://murtaza.org.uk"